version: '3.8'

services:
  rag-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: discord-proj
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app
    command: [ "uvicorn", "server:app", "--host", "0.0.0.0", "--port", "8000" ]
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    build:
      context: .
      dockerfile: Dockerfile.ollama
    ports:
      - "12345:11434"
